apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - image: {{ .Values.werf.image.grafana }}
        name: grafana
        ports:
        - containerPort: 80
          name: grafana
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: grafana
spec:
  type: NodePort
  ports:
  - name: "grafana-service"
    port: 3000
    targetPort: 80
    nodePort: 31161
  selector:
    app: grafana
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-grafana
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: grafana.devops.net.by
      http:
        paths:
          - path: /
            backend:
              serviceName: grafana
              servicePort: 3000
