apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - image: {{ .Values.werf.image.grafana }}
        name: grafana
        ports:
        - containerPort: 3000
          name: grafana
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: grafana
spec:
  type: ClusterIP
  ports:
  - name: "grafana-service"
    port: 3000
    targetPort: 3000
  selector:
    app: grafana
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-grafana
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issue: devops-cluster-cert-issuer
    kubernetes.io/tls-acme: "true"
spec:
  tls:
  - hosts:
    - "grafana.devops.net.by"
    secretName: grafana-certificate-tls
  rules:
    - host: grafana.devops.net.by
      http:
        paths:
          - path: /
            backend:
              serviceName: grafana


